apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: app1
          image: app1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: my-namespace
spec:
  selector:
    app: app1
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: app2
          image: app2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: my-namespace
spec:
  selector:
    app: app2
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: my-namespace
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app1-vs
  namespace: my-namespace
spec:
  hosts:
    - "*"
  gateways:
    - my-gateway
  http:
    - name: app1
      match:
        - uri:
            prefix: /app1/
      rewrite:
        uri: /
      route:
        - destination:
            host: app1.my-namespace.svc.cluster.local
            port:
              number: 80
    - name: app2
      match:
        - uri:
            prefix: /app2/
      rewrite:
        uri: /
      route:
        - destination:
            host: app2.my-namespace.svc.cluster.local
            port:
              number: 80

